apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-app
  labels:
    app: user-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : user-service-app
  template:
    metadata:
      labels:
        app: user-service-app
    spec:
      containers:
      - name: user-service-app
        image: utkarshagrawal1/userservice:0.0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 8085
        env:
          - name:  DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name:  mysql-secret
                key:  password
            
          - name:  DB_HOST
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: host

          - name:  USER_DB
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: userdb
                  
          - name: DB_USER
            value: root

---

kind: Service
apiVersion: v1
metadata:
  name:  user-service-svc
spec:
  selector:
    app:  user-service-app
  ports:
  - port:  80
    targetPort:  8085
